export const listFilms = [
    {
        id: 1,
        Image: require('./onepiece.jpg'),
        Title: 'One Piece - Đảo Hải Tặc',
        Year: '1999',
        Nation: 'Japan',
        Description: `Đảo Hải Tặc - One Piece là chuyện về cậu bé Monkey D. Luffy do ăn nhầm Trái Ác Quỷ, bị biến thành người cao su và sẽ không bao giờ biết bơi. 10 năm sau sự việc đó, cậu rời quê mình và kiếm đủ 10 thành viên để thành một băng hải tặc, biệt hiệu Hải tặc Mũ Rơm. Khi đó của phiêu lưu tìm kiếm kho báu One Piece bắt đầu. Trong cuộc phiêu lưu tìm kiếm One Piece, băng Hải tặc mũ rơm phải chiến đấu với nhiều băng hải tặc xấu khác cũng muốn độc chiếm One Piece và Hải quân của Chính phủ muốn diệt trừ hải tặc. Băng Hải tặc Mũ Rơm phải trải qua biết bao nhiêu khó khăn, không lùi bước với ước mơ "Trở thành Vua Hải Tặc và chiếm được kho báu One Piece".`,
    },
    {
        id: 2,
        Image: require('./chuthuatsu.jpg'),
        Title: 'Jujutsu Kaisen 2nd Season',
        Year: '2023',
        Nation: 'Japan',
        Description: `Mùa thứ 2 của Jujutsu Kaisen nè!`,
    },
    {
        id: 3,
        Image: require('./dark.jpg'),
        Title: 'Dark Gathering',
        Year: '2023',
        Nation: 'Japan',
        Description: `Keitarou, chàng trai có khả năng thu hút ma quỷ, được thuê làm gia sư cho một cô bé mang tên gọi Yayoi, người có thể trông thấy ma quỷ và đang trong công cuộc tìm kiếm con ma đã mang người mẹ của mình đi mất.`,
    },
    {
        id: 4,
        Image: require('./heo.jpg'),
        Title: 'Làm Nóng Lá Gan Chú Heo',
        Year: '2023',
        Nation: 'Japan',
        Description: `Bị biến thành lợn sau khi chuyển sinh! Cơ mà nếu được chăm nom bởi một thiếu nữ xinh đẹp thì có lẽ cuộc hành trình này cũng không tệ lắm nhỉ? Tôi, một gã Otaku tẻ nhạt, đã bị mất đi ý thức sau khi ăn gan lợn sống. Cứ ngỡ bản thân đã được chuyển sinh sang dị giới, nhưng không ngờ lại phải mang hình hài của một con heo! Và rồi Jess, cô thiếu nữ có khả năng đọc thấu nội tâm của người khác, đã cưu mang chú lợn đang phải nằm lăn lóc trong chuồng heo này. Ụt ịt! Dễ thương quá! Nhờ tầm nhìn của loài heo, tôi có thể nhìn thấy một màu trắng tinh khôi đằng sau tà váy… “À nô, em có nghe thấy tiếng nói trong đầu của anh đó…” Chết dở! Dục vọng của tôi, nó cứ rò rỉ ra!  “Nếu anh muốn, thì một chút thôi cũng được ạ”  Ế, chờ…!? Tưởng tượng mà xem, một cuộc sống dưới sự chăm sóc của cô thiếu nữ trong sáng, người cũng đã đón nhận cái dục vọng cầm thú của tôi (dù có chút e dè), thì sẽ thế nào đây. Hừm hừm, làm lợn có lẽ cũng không tệ lắm nhỉ? Đây sẽ là câu chuyện về cuộc phiêu lưu ụt ụt của chúng tôi… hoặc đáng ra đã là vậy. Thế mà Jess ơi, tại sao em lại bị người ta muốn đoạt mạng vậy hả? Nào, hỡi chú lợn vốn thiếu thốn cả ma pháp lẫn kỹ năng chiến đấu, hãy tận dụng trí tuệ, óc nhạy bén và cả khứu giác để cứu lấy cô thiếu nữ đang bị giam cầm trong cái định mệnh nghiệt ngã này! Tác phẩm thể loại fantasy, từng đoạt giải Vàng tại Dengeki Bunko Prize lần thứ 26, chuyển sinh thành lợn!`,
    },
    {
        id: 5,
        Image: require('./ragna.jpg'),
        Title: 'Ragna Crimson',
        Year: '2023',
        Nation: 'Japan',
        Description: `Ragna là một thợ săn rồng "kém cỏi". Anh có một cô em gái vô cùng mạnh mẽ. Một ngày nọ một kẻ địch cực mạnh xuất hiện, đe dọa sinh mạng của em gái Ragna. Lúc này, một nhân vật lạ mặt xuất hiện - ông ta chính là Ragna trong tương lai và đang nắm giữ một sức mạnh vô cùng lớn. Ragna tương lai căm ghét sức mạnh của mình, nhưng Ragna hiện tại thì cần nó! Tương lai trao lại sức mạnh cho quá khứ và rồi một thợ săn rồng hùng mạnh ra đời!`,
    },
    {
        id: 6,
        Image: require('./deathjpg.jpg'),
        Title: 'Dead Mount Death Play',
        Year: '2023',
        Nation: 'Japan',
        Description: `Một thể loại xuyên không nhưng là xuyên không từ thế giới fantasy sang thế giới hiện đại. một trò chơi hại não và kinh dị bắt đầu.`,
    },
    {
        id: 7,
        Image: require('./100cobangaijpg.jpg'),
        Title: '100 Cô Bạn Gái Yêu Bạn Rất Rất Rất Rất Rất Nhiều',
        Year: '2023',
        Nation: 'Japan',
        Description: `Mùa xuân là mùa của những cuộc chia li và gặp gỡ. Aijou Rentarou đã phải trải qua nỗi đau bị từ chối sau khi tỏ tình lần thứ 100 đúng vào lễ tốt nghiệp trung học của mình. Cậu ra dáng một quý ông có trái tim trong sáng và thuần khiết, mọi người xung quanh đều nói cậu có khuôn mặt và tính cách tốt. Một vị thần hôn nhân và tình yêu của ngôi đền bất ngờ xuất hiện trước Rentarou đang tuyệt vọng, nói rằng cuộc sống trung học mới sắp bắt đầu và cậu sẽ gặp 100 người bạn định mệnh và những những người không hoà hợp với cậu bằng cách nào đó sẽ phải chết. Đột nhiên, một vận mệnh Yêu hoặc Chết ×100 gây sốc được thuê dệt. Bằng cách này, những ngày xám xịt khi bị từ chối chuyển sang những ngày tươi sáng khi cậu bắt đầu tràn ngập trong hạnh phúc tình yêu! Không có luật nào nói rằng bạn không thể có 100 bạn gái? Sẽ không một ai bị bỏ rơi...!? Cuộc sống trung học harem tình yêu hài hước thuần túy kỳ lạ, mối tình đa thê đầy chân thành và tiếng sét ái tình sẽ lần lượt đưa những người định mệnh đến với nhau.`,
    },
    {
        id: 8,
        Image: require('./spyxjpg.jpg'),
        Title: 'Spy x Family Season 2',
        Year: '2023',
        Nation: 'Japan',
        Description: `Mùa thứ 2 của Spy x Family.`,
    },
    {
        id: 9,
        Image: require('./hikijpg.jpg'),
        Title: 'Hikikomari Kyuuketsuki no Monmon',
        Year: '2023',
        Nation: 'Japan',
        Description: `“… Fueh? Gì vậy? ” Khi nàng thơ hikikomori Terakomari, gọi tắt là Komari, tỉnh dậy từ cơn say ngủ, cô đột nhiên được bổ nhiệm làm chỉ huy! Và như thể đời chưa đủ khổ, quân đoàn cô chịu trách nhiệm đứng đầu được biết đến với việc đã lật đổ và sát hại thủ lĩnh của họ! Mặc dù cô được sinh ra trong một gia đình ma cà rồng danh giá, nhưng vì cô không thể uống bất kỳ loại máu nào, khả năng vận động cũng như thể chất cô gần như là con số không, cơ thể thì nhỏ hơn tuổi, thậm chí cô còn không thể sử dụng phép thuật. Trước hành lanh tuyệt vọng vô tận này, nàng Maid đáng tin cậy (!?) Vill đã có mặt để cứu vớt cô. "Để đó cho tôi, Komari-sama. Tôi đảm bảo sẽ không để ngài bị phát hiện đâu!" Bộ truyện Fantasy hài hước về cuộc tranh đấu của Komari khai màn từ đây. Dù là một hikikomori, nếu đặt hết tâm sức, liệu cô có thể làm nên chuyện?`,
    },
];
